name: Dantiao
main: com.valorin.Main
version: ${project.version}
author: Valorin
api-version: 1.13
softdepend: [ HolographicDisplays, PlaceholderAPI, TrHologram, CMI, DecentHolograms ]
commands:
  dantiao:
    description: 查看单挑插件帮助
    usage: /<command>
    aliases: [ dt ]